### ISSUE TITLE
[Notification Center] - Create a noSQL database

### ISSUE THREAD

**Issue by imqdee** [LedgerHQ/ledger-fresh-management#37]
## Header

**Name of the task**: Create a noSQL database

**Name of the module**: Notification Center

**Difficulty**: 5

**Waiting for**: /

### Short description

In order to inform the user that a challenge period has begun, we need a database that maps the address of a wallet and the communication channels associated with it.

### Full description

In Ledger Fresh, we will give the signer of a wallet the ability to specify the communication channels they want to use to inform them that a challenge period has begun. The communication channels will be stored in the noSQL database you will set up, mapped to the wallet address.

Initially, there will be 2 types of communication channels available to the user and we will only allow one value per type of communication channel for the user. The signer will have the choice to be notified by `Telegram` and/or `Email`, which means they will have to provide their Telegram ID and/or email address if they wish. 

However, since we plan to support multiple values for each type in the future, we want to configure the database with this in mind. This means that the database should be configured to accept multiple email addresses or multiple Telegram IDs for the same wallet address. On top of that, it should be easy in the future to add a new type of communication channel (say Discord for example). These are the requirements for the database.

Here's a minimalist overview of the schema we are looking for:

```typescript
type Schema = {
    id: string, // wallet address
    telegrams: string[], // handles
    emails: string[],
 }
```

You are free to use the NoSQL tech you want to.
The solution must be dockerise and tested properly.

### Additionals ressources

- /

**Comment by qd-qd** [comment]
done by https://github.com/LedgerHQ/notification-center/pull/1
